# -*- coding: utf-8 -*-
"""chances9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eks_qRAAFpcOg0bDZw1G3EFN4U1uC4_q
"""

import time 
var = 0
while var <=10:
    print(var)
    time.sleep(1)
    var +=2

from time import sleep 
itens=['ana','maria','matheus','bia','5','8','10','80']
for item in itens:  
    print(item)
    sleep(1)

sala = ['brasil',['norte',['amazonas',['manaus'],'acre',['rio branco']]],
        ['nordeste'],['paraiba',['joao pessoa'],['pernambuco',['recife']]]]

sala = []
while len(sala) <=5:
    nome = str(input('informe o nome: '))
    sala.append(nome)
for nome in sala:
    print(nome)

grupo = []
while len(grupo)<2:
    pessoa = str(input('adiciona uma pessoa: '))
    grupo.append(pessoa)
    qtd = 0 
    while qtd <= len(grupo):
        qtd+=1
    if len(grupo)<qtd:
        qtd-=1
print(qtd)

grupo = []
while True:
    acao = int(input('digite 1 para adicionar ou 2 para listar: '))
    if acao == 1:
        pessoa = str('adicionar o nome: ')
        grupo.append(pessoa)
    elif acao == 2:
            qtd = 1
            for pessoa in grupo: 
                print(f'{qtd}: {pessoa}')
                qtd+=1
            break

import random 
tentativas = 0
chances = 5 
nSecreto = random.randint(1,10)
print(nSecreto)
while chances >= 1: 
    r=int(input('adivinhe o numero: '))
    tentativas+=1
    chances-=1
    if r == nSecreto:
        print('acertou.')
        break
    else: 
        if chances >=1:
            print(f'tentativas {tentativas} - errou, o numero secreto nao e {r} ')
            print(f'voce ainda tem {chances} chances.')
        else:
            print(f'tentativas {tentativas} - errou, o numero secreto nao e {r} ')
            print('acabaram as suas chances.')

    print(nSecreto)